-- ========================================
-- AI Supermarket Demo Database Schema
-- ========================================

-- Drop tables (for reset, optional)
drop table if exists public.order_details cascade;
drop table if exists public.orders cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.customers cascade;

-- ========================================
-- 1. Categories
-- ========================================
create table public.categories (
    category_id bigint generated by default as identity primary key,
    category_name varchar(100) not null unique
);

-- ========================================
-- 2. Products
-- ========================================
create table public.products (
    product_id bigint generated by default as identity primary key,
    product_name varchar(150) not null,
    price numeric(10,2) not null check (price >= 0),
    image_url text,
    stock integer not null default 0 check (stock >= 0),
    category_id bigint not null,
    created_at timestamptz not null default now(),
    constraint fk_products_category
        foreign key (category_id)
        references public.categories(category_id)
        on delete restrict
);

-- ========================================
-- 3. Customers
-- ========================================
create table public.customers (
    customer_id bigint generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    email varchar(255) not null unique,
    phone varchar(30),
    address text,
    created_at timestamptz not null default now()
);

-- ========================================
-- 4. Orders
-- ========================================
create table public.orders (
    order_id bigint generated by default as identity primary key,
    customer_id bigint not null,
    order_date timestamptz not null default now(),
    delivery_time timestamptz,
    status varchar(30) not null default 'pending',
    total_amount numeric(10,2) not null default 0 check (total_amount >= 0),
    created_at timestamptz not null default now(),
    constraint fk_orders_customer
        foreign key (customer_id)
        references public.customers(customer_id)
        on delete restrict,
    constraint chk_orders_status
        check (status in ('pending', 'confirmed', 'scheduled', 'delivered', 'cancelled'))
);

-- ========================================
-- 5. Order Details
-- ========================================
create table public.order_details (
    order_detail_id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity integer not null check (quantity > 0),
    unit_price numeric(10,2) not null check (unit_price >= 0),
    constraint fk_order_details_order
        foreign key (order_id)
        references public.orders(order_id)
        on delete cascade,
    constraint fk_order_details_product
        foreign key (product_id)
        references public.products(product_id)
        on delete restrict
);

-- ========================================
-- Indexes (performance)
-- ========================================
create index idx_products_category_id
    on public.products(category_id);

create index idx_orders_customer_id
    on public.orders(customer_id);

create index idx_orders_delivery_time
    on public.orders(delivery_time);

create index idx_order_details_order_id
    on public.order_details(order_id);

create index idx_order_details_product_id
    on public.order_details(product_id);

-- ========================================
-- Sample Data (Categories)
-- ========================================
insert into public.categories (category_name)
values
    ('Fruits & Vegetables'),
    ('Breakfast'),
    ('Drinks'),
    ('Snacks'),
    ('Household');

-- ========================================
-- Sample Data (Products - small set)
-- ========================================
insert into public.products (product_name, price, image_url, stock, category_id)
values
    ('Milk 1L', 4.50, 'https://via.placeholder.com/150', 20, 2),
    ('Bread', 3.50, 'https://via.placeholder.com/150', 15, 2),
    ('Eggs 12pcs', 3.80, 'https://via.placeholder.com/150', 30, 2),
    ('Apple 1kg', 3.20, 'https://via.placeholder.com/150', 25, 1),
    ('Banana 1kg', 2.20, 'https://via.placeholder.com/150', 25, 1),
    ('Water 1.5L', 1.20, 'https://via.placeholder.com/150', 40, 3),
    ('Coca Cola', 2.50, 'https://via.placeholder.com/150', 35, 3),
    ('Chips', 2.80, 'https://via.placeholder.com/150', 20, 4),
    ('Chocolate', 3.00, 'https://via.placeholder.com/150', 18, 4),
    ('Laundry Detergent', 12.50, 'https://via.placeholder.com/150', 10, 5);

-- ========================================
-- End of File
-- ========================================